queryParameters:
  available:
    type: number
    description: set 1 to get products with at least one in stock or 0 to get products out of stock. By default you receive all
    default: 2
  requires_shipping:
    type: number
    description: set 1 to get products that requires shipping or 0 for products without shipping. By default you receive all
    default: 2
  accept_vendors:
    type: string
    description: comma separated list of accepted vendor ids
  exclude_vendors:
    type: string
    description: comma separated list of rejected vendor ids
  min_price:
    type: number
  max_price:
    type: number
  order:
    type: string
    description: |
      use -/+ in front of the attribute to specify the soriting direction (DESC / ASC)
      if no modifier is provided default is +
      multiple values MAY be provided comma separated
      example:
        `\<<resourcePathName>>?order=vendor,-date`
      will sort results by vendor ASC, date desc
    enum:
      - name
      - price
